[package]
name = "routing"
version = "0.1.0"
edition = "2021"

[dependencies]
storage = { path = "../storage" }
monoio = { version = "0.2.1", features = ["iouring", "sync"] }
futures = "0.3.30"
murmur3 = "0.5.2"
