// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 25.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:Value)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Value {
    // message fields
    // @@protoc_insertion_point(field:Value.type)
    pub type_: ::protobuf::EnumOrUnknown<ValueType>,
    // @@protoc_insertion_point(field:Value.data)
    pub data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:Value.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Value {
    fn default() -> &'a Value {
        <Value as ::protobuf::Message>::default_instance()
    }
}

impl Value {
    pub fn new() -> Value {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &Value| { &m.type_ },
            |m: &mut Value| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &Value| { &m.data },
            |m: &mut Value| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Value>(
            "Value",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Value {
    const NAME: &'static str = "Value";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(ValueType::VALUE_TYPE_UNSPECIFIED) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(ValueType::VALUE_TYPE_UNSPECIFIED) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if !self.data.is_empty() {
            os.write_bytes(2, &self.data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Value {
        Value::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(ValueType::VALUE_TYPE_UNSPECIFIED);
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Value {
        static instance: Value = Value {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Value {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Value").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Value {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Value {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:ValueType)
pub enum ValueType {
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_UNSPECIFIED)
    VALUE_TYPE_UNSPECIFIED = 0,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_VARCHAR)
    VALUE_TYPE_VARCHAR = 1,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_INT16)
    VALUE_TYPE_INT16 = 2,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_INT32)
    VALUE_TYPE_INT32 = 3,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_INT64)
    VALUE_TYPE_INT64 = 4,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_UNSIGNED32)
    VALUE_TYPE_UNSIGNED32 = 5,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_UNSIGNED64)
    VALUE_TYPE_UNSIGNED64 = 6,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_FLOAT32)
    VALUE_TYPE_FLOAT32 = 7,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_FLOAT64)
    VALUE_TYPE_FLOAT64 = 8,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_DECIMAL)
    VALUE_TYPE_DECIMAL = 9,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_DATETIME)
    VALUE_TYPE_DATETIME = 10,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_BOOLEAN)
    VALUE_TYPE_BOOLEAN = 11,
    // @@protoc_insertion_point(enum_value:ValueType.VALUE_TYPE_NULL)
    VALUE_TYPE_NULL = 12,
}

impl ::protobuf::Enum for ValueType {
    const NAME: &'static str = "ValueType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ValueType> {
        match value {
            0 => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSPECIFIED),
            1 => ::std::option::Option::Some(ValueType::VALUE_TYPE_VARCHAR),
            2 => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT16),
            3 => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT32),
            4 => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT64),
            5 => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSIGNED32),
            6 => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSIGNED64),
            7 => ::std::option::Option::Some(ValueType::VALUE_TYPE_FLOAT32),
            8 => ::std::option::Option::Some(ValueType::VALUE_TYPE_FLOAT64),
            9 => ::std::option::Option::Some(ValueType::VALUE_TYPE_DECIMAL),
            10 => ::std::option::Option::Some(ValueType::VALUE_TYPE_DATETIME),
            11 => ::std::option::Option::Some(ValueType::VALUE_TYPE_BOOLEAN),
            12 => ::std::option::Option::Some(ValueType::VALUE_TYPE_NULL),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ValueType> {
        match str {
            "VALUE_TYPE_UNSPECIFIED" => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSPECIFIED),
            "VALUE_TYPE_VARCHAR" => ::std::option::Option::Some(ValueType::VALUE_TYPE_VARCHAR),
            "VALUE_TYPE_INT16" => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT16),
            "VALUE_TYPE_INT32" => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT32),
            "VALUE_TYPE_INT64" => ::std::option::Option::Some(ValueType::VALUE_TYPE_INT64),
            "VALUE_TYPE_UNSIGNED32" => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSIGNED32),
            "VALUE_TYPE_UNSIGNED64" => ::std::option::Option::Some(ValueType::VALUE_TYPE_UNSIGNED64),
            "VALUE_TYPE_FLOAT32" => ::std::option::Option::Some(ValueType::VALUE_TYPE_FLOAT32),
            "VALUE_TYPE_FLOAT64" => ::std::option::Option::Some(ValueType::VALUE_TYPE_FLOAT64),
            "VALUE_TYPE_DECIMAL" => ::std::option::Option::Some(ValueType::VALUE_TYPE_DECIMAL),
            "VALUE_TYPE_DATETIME" => ::std::option::Option::Some(ValueType::VALUE_TYPE_DATETIME),
            "VALUE_TYPE_BOOLEAN" => ::std::option::Option::Some(ValueType::VALUE_TYPE_BOOLEAN),
            "VALUE_TYPE_NULL" => ::std::option::Option::Some(ValueType::VALUE_TYPE_NULL),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ValueType] = &[
        ValueType::VALUE_TYPE_UNSPECIFIED,
        ValueType::VALUE_TYPE_VARCHAR,
        ValueType::VALUE_TYPE_INT16,
        ValueType::VALUE_TYPE_INT32,
        ValueType::VALUE_TYPE_INT64,
        ValueType::VALUE_TYPE_UNSIGNED32,
        ValueType::VALUE_TYPE_UNSIGNED64,
        ValueType::VALUE_TYPE_FLOAT32,
        ValueType::VALUE_TYPE_FLOAT64,
        ValueType::VALUE_TYPE_DECIMAL,
        ValueType::VALUE_TYPE_DATETIME,
        ValueType::VALUE_TYPE_BOOLEAN,
        ValueType::VALUE_TYPE_NULL,
    ];
}

impl ::protobuf::EnumFull for ValueType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ValueType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ValueType {
    fn default() -> Self {
        ValueType::VALUE_TYPE_UNSPECIFIED
    }
}

impl ValueType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ValueType>("ValueType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ccommon.proto\";\n\x05Value\x12\x1e\n\x04type\x18\x01\x20\x01(\x0e2\
    \n.ValueTypeR\x04type\x12\x12\n\x04data\x18\x02\x20\x01(\x0cR\x04data*\
    \xc5\x02\n\tValueType\x12\x1a\n\x16VALUE_TYPE_UNSPECIFIED\x10\0\x12\x16\
    \n\x12VALUE_TYPE_VARCHAR\x10\x01\x12\x14\n\x10VALUE_TYPE_INT16\x10\x02\
    \x12\x14\n\x10VALUE_TYPE_INT32\x10\x03\x12\x14\n\x10VALUE_TYPE_INT64\x10\
    \x04\x12\x19\n\x15VALUE_TYPE_UNSIGNED32\x10\x05\x12\x19\n\x15VALUE_TYPE_\
    UNSIGNED64\x10\x06\x12\x16\n\x12VALUE_TYPE_FLOAT32\x10\x07\x12\x16\n\x12\
    VALUE_TYPE_FLOAT64\x10\x08\x12\x16\n\x12VALUE_TYPE_DECIMAL\x10\t\x12\x17\
    \n\x13VALUE_TYPE_DATETIME\x10\n\x12\x16\n\x12VALUE_TYPE_BOOLEAN\x10\x0b\
    \x12\x13\n\x0fVALUE_TYPE_NULL\x10\x0cb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Value::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ValueType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
